### ISSUE TITLE
Return Values

### ISSUE THREAD

**Issue by ethankershner** [mrsmn/coinmarketcap-api#16]
When I use the ticker() method, instead of returning a list or dictionary, it returns a string. This is difficult to work with. Is the program supposed to do this?

**Comment by skywen** [comment]
you can eval() this to turn the string into dict
----- 原始邮件 -----
发件人：ethankershner <notifications@github.com>
收件人：mrsmn/coinmarketcap-api <coinmarketcap-api@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[mrsmn/coinmarketcap-api] Return Values (#16)
日期：2017年05月25日 12点16分

When I use the ticker() method, instead of returning a list or dictionary, it returns a string. This is difficult to work with. Is the program supposed to do this?

&mdash;
